#!/bin/bash
set -e
# By SkylineIsBack

clear
echo "
   ____   _____ _____   _____ 
  / __ \ / ____|  __ \ / ____|
 | |  | | (___ | |__) | |     
 | |  | |\___ \|  ___/| |     
 | |__| |____) | |    | |____ 
  \___\_\_____/|_|     \_____|
                              "
echo ""
defaultlocation="$(dirname $(readlink -f $0))"
echo "Listing all overlays present in backup directory:"
ls $defaultlocation/backup/
echo ""
echo "Either type the name of the overlay you want to re-copy or type * for re-copying all files"
read whattocopy
su -c mount -o rw,remount /vendor
su -c cp -r $defaultlocation/backup/$whattocopy /vendor/overlay/
su -c chmod 644 /vendor/overlay/$whattocopy
echo ""
echo "Successfully pasted the overlay(s)."
echo ""
echo "Do you want to reboot the device? (y/n)"
read rebootdevice
if [[ "$rebootdevice" == "y" ]]
then
    su -c reboot
else
    echo "Exiting"
    exit
fi